
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package syntaxAnalyzer;

/** CUP generated class containing symbol constants. */
public class ToyParserSym {
  /* terminals */
  public static final int LEFTBRACKET = 45;
  public static final int PERIOD = 42;
  public static final int RIGHTBRACKET = 46;
  public static final int RIGHTPAREN = 44;
  public static final int NOTEQUAL = 35;
  public static final int DOUBLE = 6;
  public static final int GREATER = 31;
  public static final int INTERFACE = 12;
  public static final int INT = 24;
  public static final int PRINTLN = 15;
  public static final int LESS = 30;
  public static final int FOR = 9;
  public static final int MINUS = 26;
  public static final int LEFTPAREN = 43;
  public static final int SEMICOLON = 41;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int LESSEQUAL = 32;
  public static final int OR = 37;
  public static final int COMMA = 40;
  public static final int DOUBLECONSTANT = 52;
  public static final int CLASS = 5;
  public static final int NEWARRAY = 14;
  public static final int PLUS = 25;
  public static final int IF = 10;
  public static final int THIS = 19;
  public static final int ID = 50;
  public static final int INTCONSTANT = 49;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 17;
  public static final int EQUAL = 34;
  public static final int TRUE = 2;
  public static final int STRINGCONSTANT = 51;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int NULL = 23;
  public static final int MOD = 29;
  public static final int BREAK = 22;
  public static final int VOID = 20;
  public static final int READLN = 16;
  public static final int ASSIGNOP = 39;
  public static final int GREATEREQUAL = 33;
  public static final int RIGHTBRACE = 48;
  public static final int ELSE = 7;
  public static final int WHILE = 21;
  public static final int BOOLEANCONSTANT = 53;
  public static final int LEFTBRACE = 47;
  public static final int EXTENDS = 8;
  public static final int STRING = 18;
  public static final int FALSE = 3;
  public static final int DIVISION = 28;
  public static final int IMPLEMENTS = 11;
  public static final int MULTIPLICATION = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRUE",
  "FALSE",
  "BOOLEAN",
  "CLASS",
  "DOUBLE",
  "ELSE",
  "EXTENDS",
  "FOR",
  "IF",
  "IMPLEMENTS",
  "INTERFACE",
  "NEW",
  "NEWARRAY",
  "PRINTLN",
  "READLN",
  "RETURN",
  "STRING",
  "THIS",
  "VOID",
  "WHILE",
  "BREAK",
  "NULL",
  "INT",
  "PLUS",
  "MINUS",
  "MULTIPLICATION",
  "DIVISION",
  "MOD",
  "LESS",
  "GREATER",
  "LESSEQUAL",
  "GREATEREQUAL",
  "EQUAL",
  "NOTEQUAL",
  "AND",
  "OR",
  "NOT",
  "ASSIGNOP",
  "COMMA",
  "SEMICOLON",
  "PERIOD",
  "LEFTPAREN",
  "RIGHTPAREN",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "LEFTBRACE",
  "RIGHTBRACE",
  "INTCONSTANT",
  "ID",
  "STRINGCONSTANT",
  "DOUBLECONSTANT",
  "BOOLEANCONSTANT"
  };

  /* non terminals */
  static final int classdecl = 7;
  static final int field = 8;
  static final int interfacedecl = 9;
  static final int expr = 19;
  static final int constant = 23;
  static final int decl = 1;
  static final int type = 4;
  static final int variablecommplus = 25;
  static final int idcommplus = 26;
  static final int forstmt = 15;
  static final int breakstmt = 16;
  static final int stmtblock = 11;
  static final int whilestmt = 14;
  static final int program = 0;
  static final int returnstmt = 17;
  static final int declplus = 24;
  static final int variabledeclstar = 30;
  static final int prototype = 10;
  static final int formals = 6;
  static final int prototypestar = 29;
  static final int exprcommplus = 27;
  static final int ifstmt = 13;
  static final int variable = 3;
  static final int stmtstar = 31;
  static final int fieldstar = 28;
  static final int actuals = 22;
  static final int call = 21;
  static final int functiondecl = 5;
  static final int lvalue = 20;
  static final int stmt = 12;
  static final int variabledecl = 2;
  static final int printstmt = 18;
}

